### ISSUE TITLE
Support for directory append?

### ISSUE THREAD

**Issue by curldapps** [artem-karpenko/archiver-zip-encrypted#18]
Thanks for this awesome library! Wanted to see if it has support / will have support for appending a directory (like a software package directory) to the archive?

I know this requires a recursive write so I wasn't sure if it's already supported

**Comment by artem-karpenko** [comment]
Hi @curldapps,
in fact `archiver` library supports appending a directory to archive. See their API documentation for [directory method](https://www.archiverjs.com/archiver#directory).
