### ISSUE TITLE
Error extracting in WinZip for AES zipped file: central and local directory mismatch

### ISSUE THREAD

**Issue by curldapps** [artem-karpenko/archiver-zip-encrypted#19]
Hey there! I've gotten your library working in my project to zip a software executable directory and encrypted using the AES option. I'm noticing a weird behavior when decrypting/extracting the directory within my zip files where I am getting a central and local directory mismatch. Attached is a picture of the error, the zipped directory, and also of my code. My environment is a docker container running Linux. I would love to know if you can help me solve this error so that the end-user will not face errors trying to extract the software package. Thanks!

<img width="699" alt="Screen Shot 2019-12-19 at 12 12 15 PM" src="https://user-images.githubusercontent.com/56089222/71193863-dab54280-2258-11ea-87ec-99515ec47043.png">

<img width="410" alt="Screen Shot 2019-12-19 at 10 56 48 AM" src="https://user-images.githubusercontent.com/56089222/71193864-dab54280-2258-11ea-8256-42f96d2db93e.png">

              `archiver.registerFormat('zip-encrypted', require("archiver-zip-encrypted"));
        
                let entityName = result.result.ops[0].user.entityName;
                var output = fs.createWriteStream('/home/node/app/' + '/'+ entityName +'.zip');
                let archive = await archiver.create('zip-encrypted', {zlib: {level: 8}, encryptionMethod: 'aes256', password: password});
                // pipe archive data to the file
                archive.pipe(output);
                archive.on('error', function(err) {
                    throw err;
                  });
                archive.directory('/home/node/app/extension', entityName + '_extension');
                archive.finalize();`

**Comment by artem-karpenko** [comment]
Hi @curldapps,
there is indeed issue with encryption of directories, I'll try to fix it.

**Comment by curldapps** [comment]
Much appreciated - if I can be of assistance let me know!

**Comment by curldapps** [comment]
any updates on this front my friend?

**Comment by artem-karpenko** [comment]
Hi @curldapps,
sorry for the silence, got busy with work. I found and fixed the issue that made encryption of directories incorrect. Version 1.0.7 is published and ready to be used.

**Comment by artem-karpenko** [comment]
Note: it's already 1.0.8, I had to re-release it to remove accidentally introduced express dependency

**Comment by curldapps** [comment]
thanks I will test this out and then close if working. Appreciate it

**Comment by curldapps** [comment]
Fixed! thanks a bunch. I was able to clear this minor bug after testing with v1.0.8 in NodeJS 10+

Cheers
