### ISSUE TITLE
Suggest update to documentation

### ISSUE THREAD

**Issue by curldapps** [artem-karpenko/archiver-zip-encrypted#20]
Documentation in its current state recommends registering the zip-encrypted format with archiver along with the code to create the archive. If used in an API or function, this repeated call of `archiver.registerFormat('zip-encrypted', require("archiver-zip-encrypted"));` will result in errors stating that the 'format is already registered'. 

I was able to stop this from happening by registering the format using the code above inside my startup script in server.js when starting up my NodeJS process. This prevents format is already registered errors. 

I would propose changing the documentation to note that potential behavior:

```
// register format for archiver
// **will throw error if the same format is registered multiple times within one process without shutdown
archiver.registerFormat('zip-encrypted', require("archiver-zip-encrypted"));

// create archive and specify method of encryption and password
let archive = archiver.create('zip-encrypted', {zlib: {level: 8}, encryptionMethod: 'aes256', password: '123'});
archive.append('File contents', {name: 'file.name'})
// ... add contents to archive as usual using archiver
```

**Comment by artem-karpenko** [comment]
Hi @curldapps,
thank you for suggestion, I've updated README.md file accordingly to avoid confusion.
