### ISSUE TITLE
readdir-glob dependency library have issue

### ISSUE THREAD

**Issue by naisargparmar** [artem-karpenko/archiver-zip-encrypted#29]
projectbe/node_modules/readdir-glob/index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, shouldSkip, strict) {
               ^
 
 SyntaxError: Unexpected token *
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)

16:38:57 + node --version
16:38:57 v8.11.2
16:38:57 + npm --version
16:38:57 5.6.0

**Comment by artem-karpenko** [comment]
Hi @naisargparmar,
node version 8 is not supported (it's not supported by archiver package as well)
